---
title: "Syllabus"
subtitle: "This years course structure"

html:
    theme: litera
    highlight-style: breezedark
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc: true
---
# Part I 
## Introduction to Julia and Modelling

In the first part, an introduction to the basic concepts of programming in Julia and to mathematical modelling is provided. Students will learn the Julia syntax, data types, as well as how to implement loops and functions in Julia. We will introduce core Julia libraries, too, including JuMP and DataFrames. Once these concepts are understood, we will learn how they can be used to solve problems.

## Lectures

**Welcome and Introduction (I)**\
Introduction to the course and mathematical modelling

**First Steps in Julia (II)**\
Vectors, matrices, basic operations loops and functions

**Packages and Data Management (III)**\
Package Management, DataFrames, reading and writing data

**Modelling with JuMP (IV)**\
Modeling with JuMP with variables, parameters and constraints

# Part II 
## Applied Optimization with Basic Models

In the second part, we will cover applied optimization based on basic modelling concepts. We will start with the classic capacitated lot-sizing problem and learn how to model and solve it using JuMP. 

## Lectures

**Beer Production Planning (V)**\
A case study on beer brewing based on the classic capacitated lot-sizing problem

**Minimizing Split Orders in E-Commerce (VI)**\
A case study in E-Commerce based on a quadratic knapsack problem

**Periodic Library Routing (VII)**\
A case study on routing books to branches based on a capacitated vehicle routing problem

**Police Districting (VIII)**\
A case study on police districting based on a facility location problem

# Part III 
## Applied Optimization with Advanced Models

In the third part, we will cover more advanced optimisation models and concepts. We will start by looking into three different applied optimisation problems in crowd safety.

## Lectures

**Safety Planning for the Islamic Pilgrimage in Mecca (IX)**\
A case study on safety planning for the hajj pilgrimage based on time-dependent network flows

**Passenger Flow Control in Urban Rail (X)**\
A case study on passenger flow control in urban rail based on time-dependent network flows

**Arena Seat Planning under Distancing Rules (XI)**\
A case study on arena seat planning under distancing rules based on the 2-dimensional knapsack problem

**Sales Force Deployment for Teams (XII)**\
A case study on sales force deployment for teams based on a linear programming model

**Recap and Discussion (XIII)**\
We repeat the concepts from the course and discuss all your remaining questions